model:
  name: Tacotron2
  encoder_type: LSTM
  decoder_type: LSTM
  rnn_units: 1024
  mel_channels: 80
  # Other model parameters

training:
  batch_size: 16
  epochs: 1000
  learning_rate: 0.001
  validation_split: 0.1
  checkpoint_interval: 10

data:
  dataset_path: "examples/processed_data.json"  # Path to preprocessed data
  batch_size: 16
  max_input_length: 200
  max_target_length: 200
  mel_channels: 80
